### ISSUE TITLE
C++ error for botanimation.cpp

### ISSUE THREAD

**Issue by somadsul** [Cosmic-OS/platform_frameworks_base#7]
we are facing this issue for S5 G900H Exynos5 based device.
if I changed something in this file it gives bootloop, request to maintainer please give us the way to slve this

target thumb C++: bootanimation <= frameworks/base/cmds/bootanimation/BootAnimation.cpp
frameworks/base/cmds/bootanimation/BootAnimation.cpp:395:59: error: use of undeclared identifier 'IMG_ENC'
    if (encryptedAnimation && access(getAnimationFileName(IMG_ENC), R_OK) == 0)
                                                          ^
frameworks/base/cmds/bootanimation/BootAnimation.cpp:396:41: error: use of undeclared identifier 'IMG_ENC'
        fd = fopen(getAnimationFileName(IMG_ENC), "r");
                                        ^
frameworks/base/cmds/bootanimation/BootAnimation.cpp:397:42: error: use of undeclared identifier 'IMG_OEM'
    else if (access(getAnimationFileName(IMG_OEM), R_OK) == 0)
                                         ^
frameworks/base/cmds/bootanimation/BootAnimation.cpp:398:41: error: use of undeclared identifier 'IMG_OEM'
        fd = fopen(getAnimationFileName(IMG_OEM), "r");
                                        ^
frameworks/base/cmds/bootanimation/BootAnimation.cpp:399:42: error: use of undeclared identifier 'IMG_SYS'
    else if (access(getAnimationFileName(IMG_SYS), R_OK) == 0)
                                         ^
frameworks/base/cmds/bootanimation/BootAnimation.cpp:400:41: error: use of undeclared identifier 'IMG_SYS'
        fd = fopen(getAnimationFileName(IMG_SYS), "r");
                                        ^
6 errors generated.

**Comment by sagarshah1729** [comment]
You can revert this commits for now to solve the issues..
https://github.com/Cosmic-OS/platform_frameworks_base/commit/0fc23c823926e9f2ca2661575e211e9c8f1574eb
https://github.com/Cosmic-OS/platform_frameworks_base/commit/f6fbe93e436bed193f7f494380ec0c507f751136
https://github.com/Cosmic-OS/platform_frameworks_base/commit/5f73d50ae1c89834f9eb3532ccac637299bfe383

**Comment by AgentFabulous** [comment]
You don't need to revert. In your device tree, add this
`TARGET_BOOTANIMATION_PRELOAD = false`

**Comment by sagarshah1729** [comment]
Ok so now this issue is fixed..No need of reverting any commits..

https://github.com/Cosmic-OS/platform_frameworks_base/commit/e91b20fbf750855998b82f02f417d3d336f7acaa
This above commit fix the errors..
Closing the Issue as it is solved..
